image: gitpod/workspace-full-vnc:latest

ports:
- port: 6080
  onOpen: open-preview
- port: 8000

tasks:
  init: printf '%s\n' "Run \`cargo run\` and each time someone opens localhost port 8000 you get a ping in terminal"